server:
  port: ${PORT}
  url: ${SERVER_URL}

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}

rapidapi:
  webcontent:
      url: ${RAPIDAPI_WEB_URL}
      host: ${RAPIDAPI_WEB_HOST}
      apikey: ${RAPIDAPI_WEB_KEY}


  imageai:
    url:  ${RAPIDAPI_IMG_URL}
    host: ${RAPIDAPI_IMG_HOST}
    apikey: ${RAPIDAPI_IMG_KEY}

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html