# kubectl apply -f lionel-huamani-16-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lionel-huamani-16-deployment
  namespace: lionel-huamani-16-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lionel-huamani-16-deployment        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: lionel-huamani-16-deployment      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
      - name: lionel-huamani-16-container
        image: lionelhuamani/as241-proyecto:1.0   # Reemplaza con tu imagen Docker Hub
        imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
        envFrom:
        - secretRef:
            name: lionel-huamani-16-secret  # Esto cargará todos los valores como variables de entorno