# kubectl apply -f lionel-huamani-16-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: lionel-huamani-16-secret
  namespace: lionel-huamani-16-namespace
type: Opaque
data:
  PORT: ODA4MQ==

  DATABASE_URL: bW9uZ29kYitzcnY6Ly9saW9uZWw6bGlvbmVsaGwxOUBjbHVzdGVyMC54a21hbmp3Lm1vbmdvZGIubmV0   # en Base64
  DATABASE_USERNAME: MTZfbGlvbmVsX2h1YW1hbmk=  # en Base64
  
  RAPIDAPI_WEB_URL: aHR0cHM6Ly9pbnN0YWdyYW0tdmlkZW8tdHJhbnNjcmlwdC5wLnJhcGlkYXBpLmNvbQ   # en Base64
  RAPIDAPI_WEB_HOST: aW5zdGFncmFtLXZpZGVvLXRyYW5zY3JpcHQucC5yYXBpZGFwaS5jb20=   # en Base64
  RAPIDAPI_WEB_APIKEY: YzExOTU1ZmQ0Nm1zaDFiZjI1NTNlNjgxNTMxYXAxYWNlZDBqc24wZThiM2QxNTM0ZDc   # en Base64

  RAPIDAPI_IMG_URL: aHR0cHM6Ly9haS10ZXh0LXRvLWltYWdlLWdlbmVyYXRvci1mbHV4LWZyZWUtYXBpLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_IMG_HOST: YWktdGV4dC10by1pbWFnZS1nZW5lcmF0b3ItZmx1eC1mcmVlLWFwaS5wLnJhcGlkYXBpLmNvbQ=  # en Base64
  RAPIDAPI_IMG_APIKEY: YzExOTU1ZmQ0Nm1zaDFiZjI1NTNlNjgxNTMxYXAxYWNlZDBqc24wZThiM2QxNTM0ZDc   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode